#!/usr/bin/env python3
"""Native Prompt v6 launcher and v3-v6 resume compatibility path."""
from __future__ import annotations
import argparse, json, os, re, secrets, sys
from pathlib import Path
from typing import Any
from MathResearchCycleLedgerV2 import checkpoint, initialize, invoke_action, verify
from MathResearchLauncherV2 import *
from math_research_control_primitives import FileLease, read_signed_json
from math_research_launcher_cli import ALLOWED_EFFORT, preflight, research_prompt, run_segment, save, segment_paths, utc

def legacy_bundle()->dict[str,dict[str,str]]:
    scripts=Path(__file__).resolve().parent; paths={"module":scripts/"MathResearchCycleLedgerV2.py","cli":scripts/"invoke_math_research_cycle.py","project_module":scripts/"MathResearchProjectArchiveV2.py"}; return {key:{"path":str(path),"sha256":sha_file(path)} for key,path in paths.items()}

def assert_resume(manifest:dict[str,Any],run:Path)->None:
    require(manifest.get("schema_version")==1 and manifest.get("prompt_version") in {"v3","v4","v5","v6"},"Resume requires v3-v6 manifest"); require(Path(manifest.get("run_directory","")).resolve()==run.resolve(),"manifest run directory differs"); require(re.fullmatch(r"[0-9a-fA-F-]{36}",str(manifest.get("thread_id",""))) is not None,"thread ID is invalid"); require(manifest.get("goal",{}).get("confirmation")=="model_reported_via_nonce_marker","Goal bootstrap not confirmed"); process=manifest.get("process"); require(not process or not process_identity_matches(process.get("identity")),"concurrent Resume refused")
    for binding in (manifest.get("inputs",{}).get("prompt",{}).get("sha256"),manifest.get("inputs",{}).get("goal_objective",{}).get("file_sha256"),manifest.get("goal",{}).get("objective_sha256")): require(isinstance(binding,str) and re.fullmatch(r"[0-9a-f]{64}",binding),"manifest hash is invalid")

def launch_v6(*,mode:str,run_directory:Path,prompt_file:Path|None=None,goal_objective_file:Path|None=None,max_child_agents:int|None=None,model:str|None=None,reasoning_effort:str|None=None,continuation_prompt_file:Path|None=None,max_runtime_minutes:int|None=None,runner=None,attestation=None,resume_hook=None)->dict[str,Any]:
    require(mode in {"New","Resume"},"mode invalid"); run=assert_no_symlink_chain(run_directory); context=research_run_context(run,mode); path=run/"run.json"
    with FileLease("run",str(run)):
        if mode=="New":
            require(all(x is not None for x in (prompt_file,goal_objective_file,max_child_agents,model,reasoning_effort,max_runtime_minutes)) and continuation_prompt_file is None,"New invocation shape invalid"); require(reasoning_effort in ALLOWED_EFFORT and 1<=max_child_agents<=16 and 0<=max_runtime_minutes<=525600,"New envelope invalid"); prompt_path=resolve_run_input(prompt_file,run); goal_path=resolve_run_input(goal_objective_file,run); assert_fresh_run(run,[prompt_path,goal_path]); prompt=prompt_path.read_text(encoding="utf-8",errors="strict"); objective=goal_path.read_text(encoding="utf-8",errors="strict").strip(); require(0<len(objective)<=4000,"objective invalid"); metadata=parse_prompt_v6(prompt); require(metadata["max_child_agents"]==max_child_agents and metadata["model"]==model and metadata["reasoning_effort"]==reasoning_effort and metadata["max_runtime_minutes"]==max_runtime_minutes and metadata["goal_objective_sha256"]==sha_text(objective),"Prompt parameters differ"); require(context["Layout"]=="project" and metadata["project_id"]==context["ProjectId"] and metadata["project_directory_name"]==context["ProjectDirectoryName"],"project identity differs")
            policy=run/"cycle-policy.json"; tickets=run/"cycle-tickets-000.json"; policy.write_text(metadata["cycle_policy_json"],encoding="utf-8"); tickets.write_text(metadata["initial_tickets_json"],encoding="utf-8"); contract=sha_text(prompt.replace("\r\n","\n")); initialize(run,run.name,contract,policy,tickets); bindings=legacy_bundle(); manifest={"schema_version":1,"run_id":run.name,"revision":-1,"created_at_utc":utc(),"updated_at_utc":utc(),"prompt_version":"v6","prompt_header":"Math Research Orchestration Prompt v6","contract_version":metadata["contract_version"],"run_directory":str(run),"project":{"archive_schema":context["ProjectArchiveSchema"],"project_id":context["ProjectId"],"directory_name":context["ProjectDirectoryName"],"directory":context["ProjectDirectory"],"identity_sha256":metadata["project_identity_sha256"]},"invocation_mode":"new","status":"prepared","exit_reason":None,"thread_id":None,"launcher":{"pid":os.getpid(),"runtime":"python-native"},"inputs":{"prompt":{"file":prompt_path.name,"sha256":sha_file(prompt_path),"contract_binding_sha256":contract,"bytes":prompt_path.stat().st_size},"goal_objective":{"file":goal_path.name,"file_sha256":sha_file(goal_path),"normalized_sha256":sha_text(objective),"bytes":goal_path.stat().st_size},"continuations":[]},"config":{"model":model,"reasoning_effort":reasoning_effort,"web_search":metadata["web_search"],"total_round_budget":metadata["total_round_budget"],"attempt_budget":metadata["attempt_budget"],"audit_interval_attempts":metadata["audit_interval_attempts"],"max_runtime_minutes":max_runtime_minutes,"max_child_agents":max_child_agents,"max_total_agents":max_child_agents+1,"agent_stages":agent_stages(max_child_agents),"sandbox":"workspace-write","approval_policy":"never","approval_mode":"never"},"capacity":{"cli_override_status":"not_checked"},"executable":None,"preflight":None,"preflights":[],"goal":{"objective_sha256":sha_text(objective),"confirmation":"not_started","persistence_verified":False,"observed_status":None,"nonce":None},"prompt_v6":{"status":"not_started","segment_index":None,"submitted_sha256":None},"cycle_ledger":{"contract_binding_sha256":contract,**bindings,"policy":{"path":str(policy),"sha256":sha_file(policy)},"initial_tickets":{"path":str(tickets),"sha256":sha_file(tickets)},"checkpoint":checkpoint(run)},"process":None,"next_segment_index":0,"segments":[],"token_usage":{"input_tokens":0,"cached_input_tokens":0,"output_tokens":0,"reasoning_output_tokens":0},"global_config_modified":False}; save(path,manifest,True); selected=attestation or select_codex_executable(); manifest["executable"]=selected; save(path,manifest); preflight(manifest,path,selected,runner)
            nonce=secrets.token_hex(32); manifest["goal"]["nonce"]=nonce; save(path,manifest); schema=run/"goal-output-schema.json"; schema.write_text(json.dumps(goal_output_schema(sha_text(objective),nonce),indent=2),encoding="utf-8"); goal_prompt=goal_bootstrap_prompt(objective,sha_text(objective),nonce); (run/"goal-bootstrap.md").write_text(goal_prompt,encoding="utf-8"); paths=segment_paths(run,manifest["next_segment_index"],"goal"); args=codex_exec_arguments(run_directory=run,model=model,reasoning_effort=reasoning_effort,sandbox="read-only",approval_mode="never",allow_web_search=False,enable_multi_agent=False,max_child_agents=1,last_message_path=paths["last"],output_schema_path=schema); goal=run_segment(manifest,path,selected,"goal",goal_prompt,args,600,runner); marker=goal_ready_marker(goal["paths"]["last"].read_text(encoding="utf-8").strip(),sha_text(objective),nonce); manifest["thread_id"]=goal["events"]["ThreadId"]; manifest["goal"].update({"confirmation":"model_reported_via_nonce_marker","observed_status":marker["observed_status"]}); save(path,manifest); turn_prompt=research_prompt(objective,prompt,run,Path(bindings["cli"]["path"])); manifest["prompt_v6"].update({"status":"prepared","segment_index":manifest["next_segment_index"],"submitted_sha256":sha_text(turn_prompt)}); save(path,manifest); paths=segment_paths(run,manifest["next_segment_index"],"research"); args=codex_exec_arguments(run_directory=run,model=model,reasoning_effort=reasoning_effort,sandbox="workspace-write",approval_mode="never",allow_web_search=metadata["web_search"]=="allowed",enable_multi_agent=True,max_child_agents=max_child_agents,last_message_path=paths["last"],resume_thread_id=manifest["thread_id"]); turn=run_segment(manifest,path,selected,"research",turn_prompt,args,max_runtime_minutes*60 if max_runtime_minutes else 0,runner,manifest["thread_id"])
        else:
            require(continuation_prompt_file is not None and all(x is None for x in (prompt_file,goal_objective_file,max_child_agents,model,reasoning_effort,max_runtime_minutes)),"Resume invocation shape invalid"); manifest=read_signed_json(path)["payload"]; assert_resume(manifest,run); selected=attestation or select_codex_executable(); require(selected["sha256"]==manifest["executable"]["sha256"] and selected["version"]==manifest["executable"]["version"],"pinned executable differs"); continuation_path=resolve_run_input(continuation_prompt_file,run); continuation=continuation_path.read_text(encoding="utf-8",errors="strict"); require(0<len(continuation)<=65536,"continuation invalid"); prompt=(run/manifest["inputs"]["prompt"]["file"]).read_text(encoding="utf-8"); objective=(run/manifest["inputs"]["goal_objective"]["file"]).read_text(encoding="utf-8").strip(); manifest["inputs"]["continuations"].append({"file":continuation_path.name,"sha256":sha_file(continuation_path),"bytes":continuation_path.stat().st_size}); preflight(manifest,path,selected,runner)
            if resume_hook is not None: resume_hook(manifest,selected)
            turn_prompt=research_prompt(objective,prompt,run,Path(legacy_bundle()["cli"]["path"]),continuation); paths=segment_paths(run,manifest["next_segment_index"],"resume"); config=manifest["config"]; args=codex_exec_arguments(run_directory=run,model=config["model"],reasoning_effort=config["reasoning_effort"],sandbox="workspace-write",approval_mode=config.get("approval_mode","never"),allow_web_search=config["web_search"]=="allowed",enable_multi_agent=True,max_child_agents=config["max_child_agents"],last_message_path=paths["last"],resume_thread_id=manifest["thread_id"]); turn=run_segment(manifest,path,selected,"resume",turn_prompt,args,config["max_runtime_minutes"]*60 if config["max_runtime_minutes"] else 0,runner,manifest["thread_id"])
        require((turn["events"]["LastAgentMessage"] or "").strip()!="MATH_RESEARCH_GOAL_MISSING_OR_MISMATCHED","Goal continuity failed"); if_cycle=manifest.get("cycle_ledger") is not None
        if if_cycle: invoke_action("ReturnCheck",run); require(verify(run)["CleanReturn"],"cycle return is not clean"); manifest["cycle_ledger"]["checkpoint"]=checkpoint(run)
        state=manifest.get("prompt_v6") or manifest.get("prompt_v5") or manifest.get("prompt_v4");
        if isinstance(state,dict): state.update({"status":"turn_completed","turn_completed_at_utc":utc()})
        manifest.update({"status":"turn_completed","exit_reason":"research_exec_turn_completed" if mode=="New" else "resume_exec_turn_completed","process":None}); save(path,manifest); return manifest

def main(argv=None)->int:
    p=argparse.ArgumentParser(); p.add_argument("--mode","-Mode",required=True,choices=("New","Resume")); p.add_argument("--run-directory","-RunDirectory",required=True,type=Path); p.add_argument("--prompt-file","-PromptFile",type=Path); p.add_argument("--goal-objective-file","-GoalObjectiveFile",type=Path); p.add_argument("--max-child-agents","-MaxChildAgents",type=int); p.add_argument("--model","-Model"); p.add_argument("--reasoning-effort","-ReasoningEffort"); p.add_argument("--continuation-prompt-file","-ContinuationPromptFile",type=Path); p.add_argument("--max-runtime-minutes","-MaxRuntimeMinutes",type=int); a=p.parse_args(argv)
    try: m=launch_v6(mode=a.mode,run_directory=a.run_directory,prompt_file=a.prompt_file,goal_objective_file=a.goal_objective_file,max_child_agents=a.max_child_agents,model=a.model,reasoning_effort=a.reasoning_effort,continuation_prompt_file=a.continuation_prompt_file,max_runtime_minutes=a.max_runtime_minutes); print(json.dumps({"ok":True,"status":m["status"],"thread_id":m["thread_id"]},separators=(",",":"))); return 0
    except Exception as exc: print(json.dumps({"ok":False,"error":str(exc)},separators=(",",":")),file=sys.stderr); return 2
if __name__=="__main__": raise SystemExit(main())
