#!/usr/bin/env python3
"""Native v2 launcher state machine used by Linux/macOS entrypoints."""
from __future__ import annotations
import argparse, json, os, re, secrets, sys, time
from pathlib import Path
from typing import Any, Callable

from MathResearchCycleLedgerV2 import checkpoint, initialize, invoke_action, verify
from MathResearchLauncherV2 import *
from math_research_control_primitives import FileLease, assert_no_symlink_chain, read_signed_json, write_signed_json

ScriptRunner=Callable[[str,dict[str,Any]],dict[str,Any]]
ALLOWED_EFFORT={"minimal","low","medium","high","xhigh","max","ultra"}

def utc()->str: return time.strftime("%Y-%m-%dT%H:%M:%SZ",time.gmtime())
def save(path:Path,manifest:dict[str,Any],create:bool=False)->None:
    manifest["revision"]=int(manifest.get("revision",-1))+1; manifest["updated_at_utc"]=utc(); write_signed_json(path,manifest,create_key=create)

def bundle(entry:Path)->dict[str,dict[str,str]]:
    scripts=Path(__file__).resolve().parent; names={"launcher_entry":entry,"launcher_module":scripts/"MathResearchLauncherV2.py","canary_entry":scripts/"invoke_math_research_canary_v2.py","cycle_module":scripts/"MathResearchCycleLedgerV2.py","cycle_cli":scripts/"invoke_math_research_cycle_v2.py","project_module":scripts/"MathResearchProjectArchiveV2.py","project_cli":scripts/"invoke_math_research_project_v2.py","stop_cli":scripts/"stop_math_research_v2.py"}; result={}
    for key,path in names.items(): path=assert_no_symlink_chain(path); require(path.is_file() and path.parent==scripts,f"native bundle item missing: {key}"); result[key]={"path":str(path),"sha256":sha_file(path)}
    return result

def segment_paths(run:Path,index:int,kind:str)->dict[str,Path]:
    prefix=f"{index:03d}-{kind}"; return {"events":run/f"events-{prefix}.jsonl","stderr":run/f"stderr-{prefix}.log","last":run/f"last-message-{prefix}.{'json' if kind=='goal' else 'md'}"}

def default_runner(kind:str,context:dict[str,Any])->dict[str,Any]:
    timeout=context["timeout"] if context["timeout"] else 365*24*3600
    return run_attested(context["attestation"],context["arguments"],context["run"],context["prompt"],context["paths"]["events"],context["paths"]["stderr"],timeout)

def run_segment(manifest:dict[str,Any],manifest_path:Path,attestation:dict[str,Any],kind:str,prompt:str,arguments:list[str],timeout:float,runner:ScriptRunner|None=None,expected_thread:str|None=None)->dict[str,Any]:
    index=int(manifest["next_segment_index"]); paths=segment_paths(Path(manifest["run_directory"]),index,kind); require(not any(path.exists() for path in paths.values()),"segment output already exists"); segment={"index":index,"kind":kind,"status":"running","started_at_utc":utc(),"ended_at_utc":None,"events_file":paths["events"].name,"stderr_file":paths["stderr"].name,"last_message_file":paths["last"].name,"exit_code":None,"timed_out":False,"terminal_event":None,"thread_id":None,"token_usage":None}; manifest["segments"].append(segment); manifest["next_segment_index"]+=1; save(manifest_path,manifest)
    try:
        result=(runner or default_runner)(kind,{"attestation":attestation,"arguments":arguments,"run":Path(manifest["run_directory"]),"prompt":prompt,"paths":paths,"timeout":timeout,"manifest":manifest})
        segment.update({"exit_code":int(result.get("ExitCode",-1)),"timed_out":bool(result.get("TimedOut")),"ended_at_utc":utc()}); require(not segment["timed_out"] and segment["exit_code"]==0,f"{kind} process failed"); require(paths["last"].is_file() and 0<paths["last"].stat().st_size<=4*1024*1024,f"{kind} final message is missing or too large"); events=read_codex_json_log(paths["events"],expected_thread); require(events["TerminalType"]=="turn.completed",f"{kind} terminal event differs"); segment.update({"status":"turn_completed","terminal_event":events["TerminalType"],"thread_id":events["ThreadId"],"token_usage":events["Usage"],"events_sha256":sha_file(paths["events"]),"stderr_sha256":sha_file(paths["stderr"]),"last_message_sha256":sha_file(paths["last"])}); manifest["process"]=None
        for key,value in events["Usage"].items(): manifest["token_usage"][key]=int(manifest["token_usage"].get(key,0))+int(value)
        save(manifest_path,manifest); return {"segment":segment,"events":events,"paths":paths}
    except Exception:
        segment["status"]="timed_out" if segment["timed_out"] else "failed"; manifest["process"]=None; save(manifest_path,manifest); raise

def preflight(manifest:dict[str,Any],path:Path,attestation:dict[str,Any],runner:ScriptRunner|None)->None:
    run=Path(manifest["run_directory"]); index=len(manifest["preflights"])
    while (run/f"preflight-features-{index:03d}.stdout.txt").exists() or (run/f"preflight-features-{index:03d}.stderr.txt").exists(): index+=1
    out=run/f"preflight-features-{index:03d}.stdout.txt"; err=run/f"preflight-features-{index:03d}.stderr.txt"; args=codex_global_arguments(run_directory=run,model=manifest["config"]["model"],reasoning_effort="low",sandbox="workspace-write",approval_mode=manifest["config"]["approval_mode"],allow_web_search=False,enable_multi_agent=False,max_child_agents=1)+["features","list"]
    context={"attestation":attestation,"arguments":args,"run":run,"prompt":"","paths":{"events":out,"stderr":err,"last":out},"timeout":15,"manifest":manifest}; result=(runner or default_runner)("preflight",context); require(int(result.get("ExitCode",-1))==0 and not result.get("TimedOut"),"feature preflight failed"); feature_preflight_output(out.read_text(encoding="utf-8")); record={"exit_code":0,"stdout_file":out.name,"stderr_file":err.name,"stdout_sha256":sha_file(out),"stderr_sha256":sha_file(err)}; manifest["preflight"]=record; manifest["preflights"].append(record); manifest["capacity"]["cli_override_status"]="accepted_by_cli_preflight"; save(path,manifest)

def research_prompt(objective:str,prompt:str,run:Path,cycle_cli:Path,continuation:str|None=None)->str:
    lead="# Math Research continuation turn" if continuation else "# Math Research initial turn"
    extra=f"\n## User continuation\n{continuation}\n" if continuation else ""
    return f"""{lead}

Before any work, confirm the active Goal has objective SHA-256 `{sha_text(objective)}`; otherwise return exactly `MATH_RESEARCH_GOAL_MISSING_OR_MISMATCHED`.
Use the native cycle controller `{cycle_cli}` for every state transition. Work only inside `{run}`. Preserve the frozen objective and contract. Finish with ReturnCheck and leave no active attempt/audit.

## Frozen objective
{objective}
{extra}
## Approved orchestration contract
{prompt}
"""

def validate_resume(manifest:dict[str,Any],run:Path,context:dict[str,Any],live_bundle:dict[str,Any])->None:
    require(manifest.get("schema_version")==1 and manifest.get("launcher_protocol")=="math-research-launcher/v2" and manifest.get("prompt_version")=="v7","versioned_migration_required"); require(context["Layout"]=="project" and Path(manifest["run_directory"]).resolve()==run.resolve(),"resume project/run identity differs"); require(re.fullmatch(r"[0-9a-fA-F-]{36}",str(manifest.get("thread_id",""))) is not None,"resume thread ID is invalid"); require(manifest.get("goal",{}).get("confirmation")=="model_reported_via_nonce_marker","Goal bootstrap was not confirmed")
    for key,binding in live_bundle.items(): require(manifest["launcher_bundle"].get(key)==binding,f"native launcher bundle changed: {key}")
    process=manifest.get("process"); require(not process or not process_identity_matches(process.get("identity")),"concurrent Resume refused")

def launch(*,mode:str,run_directory:Path,prompt_file:Path|None=None,goal_objective_file:Path|None=None,max_child_agents:int|None=None,model:str|None=None,reasoning_effort:str|None=None,approval_mode:str|None=None,continuation_prompt_file:Path|None=None,max_runtime_minutes:int|None=None,runner:ScriptRunner|None=None,canary_invoker=None,attestation:dict[str,Any]|None=None,entry_path:Path|None=None)->dict[str,Any]:
    require(mode in {"New","Resume"},"mode is invalid"); run=assert_no_symlink_chain(run_directory); context=research_run_context(run,mode); manifest_path=run/"run.json"; entry=entry_path or Path(__file__).with_name("launch_math_research_v2.py"); live_bundle=bundle(entry)
    with FileLease("run",str(run)):
        if mode=="New":
            require(all(x is not None for x in (prompt_file,goal_objective_file,max_child_agents,model,reasoning_effort,approval_mode,max_runtime_minutes)),"New mode requires the full configuration"); require(continuation_prompt_file is None,"New rejects continuation"); require(reasoning_effort in ALLOWED_EFFORT and approval_mode in {"approve_for_me","never"} and 1<=int(max_child_agents)<=16 and 0<=int(max_runtime_minutes)<=525600,"New execution envelope is invalid")
            prompt_path=resolve_run_input(prompt_file,run); goal_path=resolve_run_input(goal_objective_file,run); require(prompt_path!=goal_path,"prompt and objective must differ"); assert_fresh_run(run,[prompt_path,goal_path]); prompt=prompt_path.read_text(encoding="utf-8",errors="strict"); objective=goal_path.read_text(encoding="utf-8",errors="strict").strip(); require(0<len(objective)<=4000,"objective length is invalid"); metadata=parse_prompt_v7(prompt); assert_metadata(metadata,max_child_agents=int(max_child_agents),model=str(model),reasoning_effort=str(reasoning_effort),approval_mode=str(approval_mode),max_runtime_minutes=int(max_runtime_minutes),goal_objective_sha256=sha_text(objective),run_context=context)
            policy=run/"cycle-policy.json"; tickets=run/"cycle-tickets-000.json"; policy.write_text(metadata["cycle_policy_json"],encoding="utf-8"); tickets.write_text(metadata["initial_tickets_json"],encoding="utf-8"); require(sha_file(policy)==metadata["cycle_policy_sha256"] and sha_file(tickets)==metadata["initial_tickets_sha256"],"written cycle inputs differ"); contract=sha_text(prompt.replace("\r\n","\n")); initialize(run,run.name,contract,policy,tickets); state=verify(run); require(state["CleanReturn"],"fresh ledger is not clean")
            manifest={"schema_version":1,"launcher_protocol":"math-research-launcher/v2","run_id":run.name,"revision":-1,"created_at_utc":utc(),"updated_at_utc":utc(),"prompt_version":"v7","contract_version":metadata["contract_version"],"run_directory":str(run),"project":{"archive_schema":context["ProjectArchiveSchema"],"project_id":context["ProjectId"],"directory_name":context["ProjectDirectoryName"],"directory":context["ProjectDirectory"],"identity_sha256":metadata["project_identity_sha256"]},"invocation_mode":"new","status":"prepared","exit_reason":None,"thread_id":None,"launcher":{"pid":os.getpid(),"runtime":"python-native","coordination_scope":"launcher_instances_only"},"launcher_bundle":live_bundle,"inputs":{"prompt":{"file":prompt_path.name,"sha256":sha_file(prompt_path),"contract_binding_sha256":contract,"bytes":prompt_path.stat().st_size},"goal_objective":{"file":goal_path.name,"file_sha256":sha_file(goal_path),"normalized_sha256":sha_text(objective),"bytes":goal_path.stat().st_size},"continuations":[]},"config":{"model":model,"reasoning_effort":reasoning_effort,"web_search":metadata["web_search"],"total_round_budget":metadata["total_round_budget"],"attempt_budget":metadata["attempt_budget"],"audit_interval_attempts":metadata["audit_interval_attempts"],"max_runtime_minutes":max_runtime_minutes,"max_child_agents":max_child_agents,"max_total_agents":max_child_agents+1,"agent_stages":agent_stages(max_child_agents),"sandbox":"workspace-write","approval_mode":approval_mode},"capacity":{"cli_override_status":"not_checked"},"executable":None,"preflight":None,"preflights":[],"goal":{"objective_sha256":sha_text(objective),"confirmation":"not_started","persistence_verified":False,"observed_status":None,"nonce":None},"prompt_v7":{"status":"not_started","segment_index":None,"submitted_sha256":None},"cycle_ledger":{"contract_binding_sha256":contract,"module":live_bundle["cycle_module"],"cli":live_bundle["cycle_cli"],"project_module":live_bundle["project_module"],"policy":{"path":str(policy),"sha256":sha_file(policy)},"initial_tickets":{"path":str(tickets),"sha256":sha_file(tickets)},"checkpoint":checkpoint(run)},"canary":None,"process":None,"next_segment_index":0,"segments":[],"token_usage":{"input_tokens":0,"cached_input_tokens":0,"output_tokens":0,"reasoning_output_tokens":0},"global_config_modified":False}; save(manifest_path,manifest,True)
            selected=attestation or select_codex_executable(); manifest["executable"]=selected; save(manifest_path,manifest); preflight(manifest,manifest_path,selected,runner)
            canary=invoke_launcher_canary(attestation=selected,run_directory=run,manifest_path=manifest_path,launcher_entry_path=entry,launcher_module_path=Path(live_bundle["launcher_module"]["path"]),canary_entry_path=Path(live_bundle["canary_entry"]["path"]),cycle_cli_path=Path(live_bundle["cycle_cli"]["path"]),approval_mode=approval_mode,model=model,reasoning_effort=reasoning_effort,web_search=metadata["web_search"],max_child_agents=max_child_agents,invoker=canary_invoker); manifest["canary"]={"passed":canary["Passed"],"reused":canary["Reused"],"receipt_path":canary["ReceiptPath"],"binding_sha256":canary["BindingSha256"]}; save(manifest_path,manifest)
            nonce=secrets.token_hex(32); schema=run/"goal-output-schema.json"; schema.write_text(json.dumps(goal_output_schema(sha_text(objective),nonce),indent=2),encoding="utf-8"); prompt_goal=goal_bootstrap_prompt(objective,sha_text(objective),nonce); (run/"goal-bootstrap.md").write_text(prompt_goal,encoding="utf-8"); paths=segment_paths(run,manifest["next_segment_index"],"goal"); args=codex_exec_arguments(run_directory=run,model=model,reasoning_effort=reasoning_effort,sandbox="workspace-write" if approval_mode=="approve_for_me" else "read-only",approval_mode=approval_mode,allow_web_search=False,enable_multi_agent=False,max_child_agents=1,last_message_path=paths["last"],output_schema_path=schema); turn=run_segment(manifest,manifest_path,selected,"goal",prompt_goal,args,600,runner); marker=goal_ready_marker(turn["paths"]["last"].read_text(encoding="utf-8").strip(),sha_text(objective),nonce); manifest["thread_id"]=turn["events"]["ThreadId"]; manifest["goal"].update({"nonce":nonce,"confirmation":"model_reported_via_nonce_marker","observed_status":marker["observed_status"]}); save(manifest_path,manifest)
            turn_prompt=research_prompt(objective,prompt,run,Path(live_bundle["cycle_cli"]["path"])); (run/"research-turn.md").write_text(turn_prompt,encoding="utf-8"); manifest["prompt_v7"].update({"status":"prepared","segment_index":manifest["next_segment_index"],"submitted_sha256":sha_text(turn_prompt)}); save(manifest_path,manifest); paths=segment_paths(run,manifest["next_segment_index"],"research"); args=codex_exec_arguments(run_directory=run,model=model,reasoning_effort=reasoning_effort,sandbox="workspace-write",approval_mode=approval_mode,allow_web_search=metadata["web_search"]=="allowed",enable_multi_agent=True,max_child_agents=max_child_agents,last_message_path=paths["last"],resume_thread_id=manifest["thread_id"]); research=run_segment(manifest,manifest_path,selected,"research",turn_prompt,args,max_runtime_minutes*60 if max_runtime_minutes else 0,runner,manifest["thread_id"])
        else:
            require(continuation_prompt_file is not None and all(x is None for x in (prompt_file,goal_objective_file,max_child_agents,model,reasoning_effort,approval_mode,max_runtime_minutes)),"Resume accepts only continuation"); manifest=read_signed_json(manifest_path)["payload"]; validate_resume(manifest,run,context,live_bundle); selected=attestation or select_codex_executable(); require(selected["sha256"]==manifest["executable"]["sha256"] and selected["version"]==manifest["executable"]["version"],"pinned executable differs"); continuation_path=resolve_run_input(continuation_prompt_file,run); continuation=continuation_path.read_text(encoding="utf-8",errors="strict"); require(0<len(continuation)<=65536,"continuation length invalid"); original=(run/manifest["inputs"]["prompt"]["file"]).read_text(encoding="utf-8"); objective=(run/manifest["inputs"]["goal_objective"]["file"]).read_text(encoding="utf-8").strip(); manifest["inputs"]["continuations"].append({"file":continuation_path.name,"sha256":sha_file(continuation_path),"bytes":continuation_path.stat().st_size}); preflight(manifest,manifest_path,selected,runner); canary=invoke_launcher_canary(attestation=selected,run_directory=run,manifest_path=manifest_path,launcher_entry_path=entry,launcher_module_path=Path(live_bundle["launcher_module"]["path"]),canary_entry_path=Path(live_bundle["canary_entry"]["path"]),cycle_cli_path=Path(live_bundle["cycle_cli"]["path"]),approval_mode=manifest["config"]["approval_mode"],model=manifest["config"]["model"],reasoning_effort=manifest["config"]["reasoning_effort"],web_search=manifest["config"]["web_search"],max_child_agents=manifest["config"]["max_child_agents"],invoker=canary_invoker); turn_prompt=research_prompt(objective,original,run,Path(live_bundle["cycle_cli"]["path"]),continuation); paths=segment_paths(run,manifest["next_segment_index"],"resume"); args=codex_exec_arguments(run_directory=run,model=manifest["config"]["model"],reasoning_effort=manifest["config"]["reasoning_effort"],sandbox="workspace-write",approval_mode=manifest["config"]["approval_mode"],allow_web_search=manifest["config"]["web_search"]=="allowed",enable_multi_agent=True,max_child_agents=manifest["config"]["max_child_agents"],last_message_path=paths["last"],resume_thread_id=manifest["thread_id"]); research=run_segment(manifest,manifest_path,selected,"resume",turn_prompt,args,manifest["config"]["max_runtime_minutes"]*60 if manifest["config"]["max_runtime_minutes"] else 0,runner,manifest["thread_id"])
        message=research["events"]["LastAgentMessage"] or ""; require(message.strip()!="MATH_RESEARCH_GOAL_MISSING_OR_MISMATCHED","Goal continuity failed"); invoke_action("ReturnCheck",run); state=verify(run); require(state["CleanReturn"],"cycle ReturnCheck is not clean"); manifest["cycle_ledger"]["checkpoint"]=checkpoint(run); manifest["prompt_v7"].update({"status":"turn_completed","turn_completed_at_utc":utc()}); manifest.update({"status":"turn_completed","exit_reason":"research_exec_turn_completed" if mode=="New" else "resume_exec_turn_completed","process":None}); save(manifest_path,manifest); return manifest

def main(argv=None)->int:
    p=argparse.ArgumentParser(); p.add_argument("--mode","-Mode",choices=("New","Resume"),required=True); p.add_argument("--run-directory","-RunDirectory",type=Path,required=True); p.add_argument("--prompt-file","-PromptFile",type=Path); p.add_argument("--goal-objective-file","-GoalObjectiveFile",type=Path); p.add_argument("--max-child-agents","-MaxChildAgents",type=int); p.add_argument("--model","-Model"); p.add_argument("--reasoning-effort","-ReasoningEffort"); p.add_argument("--approval-mode","-ApprovalMode"); p.add_argument("--continuation-prompt-file","-ContinuationPromptFile",type=Path); p.add_argument("--max-runtime-minutes","-MaxRuntimeMinutes",type=int); a=p.parse_args(argv)
    try: result=launch(mode=a.mode,run_directory=a.run_directory,prompt_file=a.prompt_file,goal_objective_file=a.goal_objective_file,max_child_agents=a.max_child_agents,model=a.model,reasoning_effort=a.reasoning_effort,approval_mode=a.approval_mode,continuation_prompt_file=a.continuation_prompt_file,max_runtime_minutes=a.max_runtime_minutes); print(json.dumps({"ok":True,"run_id":result["run_id"],"status":result["status"],"thread_id":result["thread_id"]},separators=(",",":"))); return 0
    except Exception as exc: print(json.dumps({"ok":False,"error":str(exc)},separators=(",",":")),file=sys.stderr); return 2

if __name__=="__main__": raise SystemExit(main())
