#!/usr/bin/env python3
from __future__ import annotations
import json, os, sys, tempfile, unittest, uuid
from pathlib import Path
from MathResearchCycleLedgerV2 import initialize as initialize_cycle
from MathResearchLauncherV2 import *
from MathResearchLauncherV2 import _json_block, _metadata, _downgrade_prompt
from invoke_math_research_canary_v2 import invoke as invoke_canary
from math_research_control_primitives import write_signed_json
from math_research_launcher_cli import launch
from math_research_launcher_v6_cli import launch_v6


class LauncherNativeTests(unittest.TestCase):
    def setUp(self):
        self.temp=tempfile.TemporaryDirectory(); self.root=Path(self.temp.name); self.old=os.environ.get("MATH_RESEARCH_CONTROL_HOME"); control=self.root/"control"; control.mkdir(mode=0o700); os.chmod(control,0o700); os.environ["MATH_RESEARCH_CONTROL_HOME"]=str(control)
    def tearDown(self):
        if self.old is None: os.environ.pop("MATH_RESEARCH_CONTROL_HOME",None)
        else: os.environ["MATH_RESEARCH_CONTROL_HOME"]=self.old
        self.temp.cleanup()

    def prompt_v7(self):
        policy=compact_json({"schema_version":3,"protocol":"math-research-cycle-policy/v3","total_round_budget":4,"attempt_budget":2,"audit_interval_attempts":1,"max_route_family_attempts_per_cycle":2,"max_repair_batches_per_attempt":1,"audit_roles":["skeptic_quantifiers","skeptic_strategy","theory_tool_scout"]}); tickets=compact_json({"schema_version":3,"cycle_id":"cycle-1","tickets":[{"attempt_kind":"route_execution"}]}); identity=project_identity_sha256(1,"project-0001","project-one"); metadata={"schema":"7","approval_mode":"approve_for_me","contract_version":"v1","model":"gpt-test","reasoning_effort":"high","web_search":"denied","total_round_budget":"4","attempt_budget":"2","audit_interval_attempts":"1","max_child_agents":"3","max_total_agents":"4","max_runtime_minutes":"0","goal_objective_sha256":"a"*64,"cycle_policy_sha256":sha_text(policy),"initial_tickets_sha256":sha_text(tickets),"project_archive_schema":"1","project_id":"project-0001","project_directory_name":"project-one","project_identity_sha256":identity}; lines="\n".join(f"{k}: {v}" for k,v in metadata.items()); headings="\n".join(x.format(contract_version="v1") for x in V4_HEADINGS); rules="\n".join(V4_SENTINELS+V6_SENTINELS); return f"# Math Research Orchestration Prompt v7\n<!-- math-research-launcher\n{lines}\n-->\n{headings}\n{rules}\n<!-- math-research-cycle-policy\n{policy}\n-->\n<!-- math-research-initial-tickets\n{tickets}\n-->\n"

    def test_prompt_v7_and_parameter_authority(self):
        prompt=self.prompt_v7(); metadata=parse_prompt_v7(prompt); self.assertEqual((7,"approve_for_me"),(metadata["schema"],metadata["approval_mode"])); context={"Layout":"project","ProjectArchiveSchema":1,"ProjectId":"project-0001","ProjectDirectoryName":"project-one"}; self.assertTrue(assert_metadata(metadata,max_child_agents=3,model="gpt-test",reasoning_effort="high",approval_mode="approve_for_me",max_runtime_minutes=0,goal_objective_sha256="a"*64,run_context=context))
        with self.assertRaises(LauncherError): parse_prompt_v7(prompt.replace("approval_mode: approve_for_me","approval_mode: on-request"))
        with self.assertRaises(LauncherError): assert_metadata(metadata,max_child_agents=3,model="gpt-test",reasoning_effort="high",approval_mode="never",max_runtime_minutes=0,goal_objective_sha256="a"*64)

    def test_argv_feature_and_goal_json(self):
        argv=codex_exec_arguments(run_directory=self.root,model="gpt",reasoning_effort="high",sandbox="workspace-write",approval_mode="approve_for_me",allow_web_search=True,enable_multi_agent=True,max_child_agents=3,last_message_path=self.root/"last.json",ephemeral=True); self.assertEqual(1,argv.count("--approve-for-me")); self.assertNotIn("-a",argv); self.assertIn("agents.max_threads=3",argv); self.assertIn("--search",argv); self.assertTrue(feature_preflight_output("goals stable true\nmulti_agent stable true\nmulti_agent_v2 stable false\n")); marker=compact_json({"marker":"MATH_RESEARCH_GOAL_READY","nonce":"n","objective_sha256":"a"*64,"observed_status":"active"}); self.assertEqual("active",goal_ready_marker(marker,"a"*64,"n")["observed_status"])

    def test_jsonl_strict_terminal_and_usage(self):
        thread=str(uuid.uuid4()); path=self.root/"events.jsonl"; events=[{"type":"thread.started","thread_id":thread},{"type":"item.completed","item":{"type":"agent_message","text":"done"}},{"type":"turn.completed","usage":{"input_tokens":10,"output_tokens":3}}]; path.write_text("\n".join(compact_json(x) for x in events)+"\n",encoding="utf-8"); result=read_codex_json_log(path,thread); self.assertEqual(("done",10,3),(result["LastAgentMessage"],result["Usage"]["input_tokens"],result["Usage"]["output_tokens"])); path.write_text(path.read_text(encoding="utf-8")+compact_json(events[-1])+"\n",encoding="utf-8")
        with self.assertRaises(LauncherError): read_codex_json_log(path)

    def test_context_fresh_boundary_and_environment(self):
        project=self.root/"project"; run=project/"runs/r1"; run.mkdir(parents=True); (project/"project.json").write_text(json.dumps({"schema":1,"project_id":"project-0001","project_directory_name":"project"}),encoding="utf-8"); self.assertEqual("project",research_run_context(run,"New")["Layout"]); allowed=run/"prompt.md"; allowed.write_text("x",encoding="utf-8"); self.assertTrue(assert_fresh_run(run,[allowed])); extra=run/"extra"; extra.write_text("x",encoding="utf-8")
        with self.assertRaises(LauncherError): assert_fresh_run(run,[allowed])
        old=os.environ.get("OPENAI_API_KEY"); os.environ["OPENAI_API_KEY"]="private"
        try: self.assertNotIn("OPENAI_API_KEY",sanitized_environment())
        finally:
            if old is None: os.environ.pop("OPENAI_API_KEY",None)
            else: os.environ["OPENAI_API_KEY"]=old

    def test_attested_process_timeout(self):
        executable=Path(sys.executable).resolve(); attestation=executable_attestation(executable,executable.parent); out=self.root/"out"; err=self.root/"err"; result=run_attested(attestation,["-c","import time; time.sleep(3)"],self.root,"",out,err,0.2); self.assertTrue(result["TimedOut"]); self.assertFalse(process_identity_matches(result["Identity"]))

    def test_native_canary_is_read_only(self):
        project=self.root/"project"; run=project/"runs/run-1"; run.mkdir(parents=True); (project/"project.json").write_text(json.dumps({"schema":1,"project_id":"project-0001","project_directory_name":"project"}),encoding="utf-8"); policy={"schema_version":1,"protocol":"math-research-cycle-policy/v1","total_round_budget":4,"attempt_budget":2,"audit_interval_attempts":1,"max_route_family_attempts_per_cycle":2,"max_repair_batches_per_attempt":1,"audit_roles":["skeptic_quantifiers","skeptic_strategy","theory_tool_scout"]}; tickets={"schema_version":1,"cycle_id":"cycle-1","tickets":[{"ticket_id":"t1","route_family_id":"r","mechanism_id":"m","bottleneck_id":"b","decision_question":"q","search_domain":"d","success_signal":"s","stop_signal":"x","resource_caps":{"minutes":1},"reopen_condition":"new"}]}; (run/"cycle-policy.json").write_text(json.dumps(policy),encoding="utf-8"); (run/"cycle-tickets-000.json").write_text(json.dumps(tickets),encoding="utf-8"); initialize_cycle(run,"run-1","a"*64,Path("cycle-policy.json"),Path("cycle-tickets-000.json")); manifest=run/"run.json"; write_signed_json(manifest,{"run_id":"run-1"}); canary=Path(__file__).with_name("invoke_math_research_canary_v2.py"); cycle=Path(__file__).with_name("invoke_math_research_cycle_v2.py"); challenge={"schema_version":2,"protocol":"math-research-launcher-canary/v2","nonce":"b"*64,"run_directory":str(run.resolve()),"manifest_path":str(manifest.resolve()),"manifest_sha256":sha_file(manifest),"canary_entry_path":str(canary.resolve()),"canary_entry_sha256":sha_file(canary),"cycle_cli_path":str(cycle.resolve()),"cycle_cli_sha256":sha_file(cycle)}; path=run/"launcher-canary-challenge-v2.json"; path.write_text(json.dumps(challenge),encoding="utf-8"); evidence=invoke_canary(run,path,sha_file(path)); self.assertEqual(evidence["ledger_before_sha256"],evidence["ledger_after_sha256"]); self.assertEqual((0,0),(evidence["attempt_count"],evidence["total_round_count"]))

    def test_canary_orchestrator_signed_receipt_and_reuse(self):
        project=self.root/"project"; run=project/"runs/run-1"; run.mkdir(parents=True); (project/"project.json").write_text(json.dumps({"schema":1,"project_id":"project-0001","project_directory_name":"project"}),encoding="utf-8"); policy={"schema_version":1,"protocol":"math-research-cycle-policy/v1","total_round_budget":4,"attempt_budget":2,"audit_interval_attempts":1,"max_route_family_attempts_per_cycle":2,"max_repair_batches_per_attempt":1,"audit_roles":["skeptic_quantifiers","skeptic_strategy","theory_tool_scout"]}; tickets={"schema_version":1,"cycle_id":"cycle-1","tickets":[{"ticket_id":"t1","route_family_id":"r","mechanism_id":"m","bottleneck_id":"b","decision_question":"q","search_domain":"d","success_signal":"s","stop_signal":"x","resource_caps":{"minutes":1},"reopen_condition":"new"}]}; (run/"cycle-policy.json").write_text(json.dumps(policy),encoding="utf-8"); (run/"cycle-tickets-000.json").write_text(json.dumps(tickets),encoding="utf-8"); initialize_cycle(run,"run-1","a"*64,Path("cycle-policy.json"),Path("cycle-tickets-000.json")); manifest=run/"run.json"; write_signed_json(manifest,{"run_id":"run-1"}); scripts=Path(__file__).parent; canary=scripts/"invoke_math_research_canary_v2.py"; cycle=scripts/"invoke_math_research_cycle_v2.py"; launcher=scripts/"MathResearchLauncherV2.py"; attestation=executable_attestation(Path(sys.executable).resolve(),Path(sys.executable).resolve().parent)
        def fake(context):
            challenge=run/"launcher-canary-challenge-v2.json"; invoke_canary(run,challenge,sha_file(challenge)); thread=str(uuid.uuid4()); context["StdoutPath"].write_text("\n".join((compact_json({"type":"thread.started","thread_id":thread}),compact_json({"type":"item.completed","item":{"type":"agent_message","text":"ok"}}),compact_json({"type":"turn.completed","usage":{"input_tokens":1,"output_tokens":1}})))+"\n",encoding="utf-8"); context["StderrPath"].write_text("",encoding="utf-8"); context["LastMessagePath"].write_text(compact_json({"marker":"MATH_RESEARCH_LAUNCHER_CANARY_V2_OK"}),encoding="utf-8"); return {"ExitCode":0,"TimedOut":False,"OutputLimitExceeded":False}
        kwargs=dict(attestation=attestation,run_directory=run,manifest_path=manifest,launcher_entry_path=Path(__file__),launcher_module_path=launcher,canary_entry_path=canary,cycle_cli_path=cycle,approval_mode="approve_for_me",model="gpt-test",reasoning_effort="high",web_search="denied",max_child_agents=3,invoker=fake); first=invoke_launcher_canary(**kwargs); second=invoke_launcher_canary(**kwargs); self.assertTrue(first["Passed"] and not first["Reused"]); self.assertTrue(second["Passed"] and second["Reused"]); self.assertTrue((run/"launcher-canary-v2.json").is_file()); self.assertFalse((run/"launcher-canary-challenge-v2.json").exists())

    def test_native_launcher_new_and_resume_end_to_end(self):
        project=self.root/"project"; run=project/"runs/run-1"; run.mkdir(parents=True); (project/"project.json").write_text(json.dumps({"schema":1,"project_id":"project-0001","project_directory_name":"project"}),encoding="utf-8"); objective="prove a frozen test theorem"; prompt=self.prompt_v7().replace("goal_objective_sha256: "+"a"*64,"goal_objective_sha256: "+sha_text(objective)).replace("project_directory_name: project-one","project_directory_name: project").replace("project_identity_sha256: "+project_identity_sha256(1,"project-0001","project-one"),"project_identity_sha256: "+project_identity_sha256(1,"project-0001","project")); old_tickets=_json_block(prompt,"math-research-initial-tickets"); ticket={"ticket_id":"t1","route_family_id":"r","mechanism_id":"m","bottleneck_id":"b","decision_question":"q","search_domain":"d","success_signal":"s","stop_signal":"x","resource_caps":{"minutes":1},"reopen_condition":"new","route_id":"route-1","route_fingerprint_sha256":"b"*64,"attempt_kind":"route_execution"}; new_tickets=compact_json({"schema_version":3,"cycle_id":"cycle-1","tickets":[ticket]}); prompt=prompt.replace("initial_tickets_sha256: "+sha_text(old_tickets),"initial_tickets_sha256: "+sha_text(new_tickets)).replace(old_tickets,new_tickets); prompt_file=run/"prompt.md"; goal_file=run/"goal.md"; prompt_file.write_text(prompt,encoding="utf-8"); goal_file.write_text(objective,encoding="utf-8"); thread=str(uuid.uuid4()); executable=Path(sys.executable).resolve(); attestation=executable_attestation(executable,executable.parent)
        def runner(kind,context):
            paths=context["paths"]
            if kind=="preflight": paths["events"].write_text("goals stable true\nmulti_agent stable true\nmulti_agent_v2 stable false\n",encoding="utf-8"); paths["stderr"].write_text("",encoding="utf-8"); return {"ExitCode":0,"TimedOut":False}
            message=compact_json({"marker":"MATH_RESEARCH_GOAL_READY","nonce":context["manifest"]["goal"].get("nonce") or "","objective_sha256":sha_text(objective),"observed_status":"active"}) if kind=="goal" else "clean return"; paths["events"].write_text("\n".join((compact_json({"type":"thread.started","thread_id":thread}),compact_json({"type":"item.completed","item":{"type":"agent_message","text":message}}),compact_json({"type":"turn.completed","usage":{"input_tokens":2,"output_tokens":1}})))+"\n",encoding="utf-8"); paths["stderr"].write_text("",encoding="utf-8"); paths["last"].write_text(message,encoding="utf-8"); return {"ExitCode":0,"TimedOut":False}
        def canary(context):
            challenge=run/"launcher-canary-challenge-v2.json"; invoke_canary(run,challenge,sha_file(challenge)); context["StdoutPath"].write_text("\n".join((compact_json({"type":"thread.started","thread_id":str(uuid.uuid4())}),compact_json({"type":"turn.completed","usage":{}})))+"\n",encoding="utf-8"); context["StderrPath"].write_text("",encoding="utf-8"); context["LastMessagePath"].write_text(compact_json({"marker":"MATH_RESEARCH_LAUNCHER_CANARY_V2_OK"}),encoding="utf-8"); return {"ExitCode":0,"TimedOut":False}
        # The Goal nonce is persisted before the runner observes it.
        original_runner=runner
        def nonce_runner(kind,context):
            if kind=="goal":
                match=re.search(r"- nonce: `([0-9a-f]{64})`",context["prompt"]); context["manifest"]["goal"]["nonce"]=match.group(1)
            return original_runner(kind,context)
        first=launch(mode="New",run_directory=run,prompt_file=prompt_file,goal_objective_file=goal_file,max_child_agents=3,model="gpt-test",reasoning_effort="high",approval_mode="approve_for_me",max_runtime_minutes=0,runner=nonce_runner,canary_invoker=canary,attestation=attestation,entry_path=Path(__file__)); self.assertEqual(("turn_completed",thread),(first["status"],first["thread_id"])); continuation=run/"continue.md"; continuation.write_text("continue the same route",encoding="utf-8"); second=launch(mode="Resume",run_directory=run,continuation_prompt_file=continuation,runner=nonce_runner,canary_invoker=canary,attestation=attestation,entry_path=Path(__file__)); self.assertEqual("resume_exec_turn_completed",second["exit_reason"]); self.assertEqual(3,len(second["segments"]))

    def test_native_v6_launcher_new_and_resume(self):
        project=self.root/"project"; run=project/"runs/run-1"; run.mkdir(parents=True); (project/"project.json").write_text(json.dumps({"schema":1,"project_id":"project-0001","project_directory_name":"project"}),encoding="utf-8"); objective="frozen legacy objective"; prompt=self.prompt_v7().replace("goal_objective_sha256: "+"a"*64,"goal_objective_sha256: "+sha_text(objective)).replace("project_directory_name: project-one","project_directory_name: project").replace("project_identity_sha256: "+project_identity_sha256(1,"project-0001","project-one"),"project_identity_sha256: "+project_identity_sha256(1,"project-0001","project")); old=_json_block(prompt,"math-research-initial-tickets"); ticket={"ticket_id":"t1","route_family_id":"r","mechanism_id":"m","bottleneck_id":"b","decision_question":"q","search_domain":"d","success_signal":"s","stop_signal":"x","resource_caps":{"minutes":1},"reopen_condition":"new","route_id":"route-1","route_fingerprint_sha256":"b"*64,"attempt_kind":"route_execution"}; new=compact_json({"schema_version":3,"cycle_id":"cycle-1","tickets":[ticket]}); prompt=prompt.replace("initial_tickets_sha256: "+sha_text(old),"initial_tickets_sha256: "+sha_text(new)).replace(old,new); _,_,match=_metadata(prompt,7); prompt=_downgrade_prompt(prompt,match,7,6,{"approval_mode"}); pf=run/"prompt.md"; gf=run/"goal.md"; pf.write_text(prompt,encoding="utf-8"); gf.write_text(objective,encoding="utf-8"); thread=str(uuid.uuid4()); executable=Path(sys.executable).resolve(); attestation=executable_attestation(executable,executable.parent)
        def runner(kind,context):
            paths=context["paths"]
            if kind=="preflight": paths["events"].write_text("goals stable true\nmulti_agent stable true\nmulti_agent_v2 stable false\n",encoding="utf-8"); paths["stderr"].write_text("",encoding="utf-8"); return {"ExitCode":0,"TimedOut":False}
            nonce=context["manifest"]["goal"].get("nonce"); message=compact_json({"marker":"MATH_RESEARCH_GOAL_READY","nonce":nonce,"objective_sha256":sha_text(objective),"observed_status":"active"}) if kind=="goal" else "clean"; paths["events"].write_text("\n".join((compact_json({"type":"thread.started","thread_id":thread}),compact_json({"type":"item.completed","item":{"type":"agent_message","text":message}}),compact_json({"type":"turn.completed","usage":{}})))+"\n",encoding="utf-8"); paths["stderr"].write_text("",encoding="utf-8"); paths["last"].write_text(message,encoding="utf-8"); return {"ExitCode":0,"TimedOut":False}
        first=launch_v6(mode="New",run_directory=run,prompt_file=pf,goal_objective_file=gf,max_child_agents=3,model="gpt-test",reasoning_effort="high",max_runtime_minutes=0,runner=runner,attestation=attestation); continuation=run/"continue.md"; continuation.write_text("same route",encoding="utf-8"); second=launch_v6(mode="Resume",run_directory=run,continuation_prompt_file=continuation,runner=runner,attestation=attestation); self.assertEqual(("v6","never","resume_exec_turn_completed"),(second["prompt_version"],second["config"]["approval_mode"],second["exit_reason"])); self.assertEqual(3,len(second["segments"]))

    def test_legacy_compat_entrypoint_smoke_and_fail_closed(self):
        scripts=Path(__file__).parent
        for name in ("launch_math_research.py","launch_math_research_legacy_v1_compat.py","launch_math_research_legacy_v1_compat_v2.py","invoke_math_research_legacy_v1_compat_canary_host.py","invoke_math_research_legacy_v1_compat_canary_host_v2.py"):
            completed=subprocess.run([sys.executable,"-B",str(scripts/name),"--help"],capture_output=True,text=True); self.assertEqual(0,completed.returncode,name)
        blocked=subprocess.run([sys.executable,"-B",str(scripts/"launch_math_research_legacy_v1_compat.py"),"--mode","New","--run-directory",str(self.root),"--continuation-prompt-file",str(self.root/"x"),"--migration-receipt-file",str(self.root/"r")],capture_output=True,text=True); self.assertEqual(2,blocked.returncode); self.assertIn("Resume-only",blocked.stderr)

    def test_bundle_receipt_fails_mixed_path(self):
        files=[]
        for name in range(8): path=self.root/f"f{name}"; path.write_text(str(name),encoding="utf-8"); files.append(path)
        bundle={"ModulePath":files[0],"ModuleSha256":sha_file(files[0]),"CliPath":files[1],"CliSha256":sha_file(files[1]),"ProjectModulePath":files[2],"ProjectModuleSha256":sha_file(files[2]),"ProjectCliPath":files[3],"ProjectCliSha256":sha_file(files[3]),"LauncherModulePath":files[4],"LauncherModuleSha256":sha_file(files[4]),"LauncherEntryPath":files[5],"LauncherEntrySha256":sha_file(files[5]),"CanaryEntryPath":files[6],"CanaryEntrySha256":sha_file(files[6]),"StopCliPath":files[7],"StopCliSha256":sha_file(files[7])}; bind=lambda p:{"path":str(p),"sha256":sha_file(p)}; manifest={"launcher_protocol":"math-research-launcher/v2","prompt_version":"v7","cycle_ledger":{"module":bind(files[0]),"cli":bind(files[1]),"project_module":bind(files[2])},"launcher_bundle":{"cycle_module":bind(files[0]),"cycle_cli":bind(files[1]),"project_module":bind(files[2]),"project_cli":bind(files[3]),"launcher_module":bind(files[4]),"launcher_entry":bind(files[5]),"canary_entry":bind(files[6]),"stop_cli":bind(files[7])}}; self.assertTrue(assert_bundle_receipt(bundle,manifest)); manifest["launcher_bundle"]["cycle_cli"]["path"]=str(files[7])
        with self.assertRaises(LauncherError): assert_bundle_receipt(bundle,manifest)


if __name__=="__main__": unittest.main()
